apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redisharedis
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redisharedis
    spec:
      volumes:
      - name: redismount
        emptyDir: {}
      containers:
        - name: redisharedis
          image: aozdemir/redisharedis:v6          
          resources:
            limits:
              cpu: "1"
              memory: "800Mi"
            requests:
              cpu: "0.1"
              memory: "200Mi"
          ports:
            - containerPort: 6379
        - name: redishanodejsrediswatcher
          image: aozdemir/redishanodejsrediswatcher:v5
          volumeMounts:
          - name: redismount
            mountPath: /usr/share/redis
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
            - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: redisharedis-service
  labels:
    name: redisharedis-service
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: nodejs
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: redisharedis
  type: ClusterIP