---
apiVersion: v1
kind: Pod
metadata:
  name: redishapod1
  labels:
    app: redishapod1
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: "redis-pvc"
  containers:
    - name: redisharedis
      image: aozdemir/redisharedis
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /usr/share/redis
          name: data
      resources:
        limits:
          cpu: "1"
          memory: "800Mi"
        requests:
          cpu: "0.1"
          memory: "200Mi"
      ports:
        - containerPort: 6379
          name: redis
        - containerPort: 80
          name: node
---
apiVersion: v1
kind: Pod
metadata:
  name: redishapod2
  labels:
    app: redishapod2
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: "redis-pvc"
  containers:
    - name: redisharedis
      image: aozdemir/redisharedis
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /usr/share/redis
          name: data
      resources:
        limits:
          cpu: "1"
          memory: "800Mi"
        requests:
          cpu: "0.1"
          memory: "200Mi"
      ports:
        - containerPort: 6379
          name: redis
        - containerPort: 80
          name: node
---
apiVersion: v1
kind: Pod
metadata:
  name: redishapod3
  labels:
    app: redishapod3
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: "redis-pvc"
  containers:
    - name: redisharedis
      image: aozdemir/redisharedis
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /usr/share/redis
          name: data
      resources:
        limits:
          cpu: "1"
          memory: "800Mi"
        requests:
          cpu: "0.1"
          memory: "200Mi"
      ports:
        - containerPort: 6379
          name: redis
        - containerPort: 80
          name: node
---
apiVersion: v1
kind: Service
metadata:
  name: redishapod1-service
  labels:
    name: redishapod1-service
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: nodejs
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: redishapod1
  type: ClusterIP
---

