kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/usr/share/redis"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redismaster
  labels:
    app: redismaster
spec:
  replicas: 1
  selector:
    app: redismaster
  template:
    metadata:
      name: redis
      labels:
        app: redismaster
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "redis-pvc"
      containers:
        - name: redisharedis
          image: aozdemir/redisharedis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 80
              name: node
          volumeMounts:
            - mountPath: /usr/share/redis
              name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redisslave
  labels:
    app: redisslave
spec:
  replicas: 3
  selector:
    app: redisslave
  template:
    metadata:
      name: redis
      labels:
        app: redisslave
    spec:
      containers:
        - name: redisharedis
          image: aozdemir/redisharedis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 80
              name: node
---
apiVersion: v1
kind: Service
metadata:
  name: redishapod1-service
  labels:
    name: redishapod1-service
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: nodejs
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: redismaster
  type: ClusterIP
---

