apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-engineering
 annotations:
   volume.beta.kubernetes.io/storage-class: fast2
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi