apiVersion: v1
kind: Service
metadata:
  name: redis-replica-service
  labels:
    name: redis-replica-service
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redisreplica
  type: ClusterIP
