apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  labels:
    name: redis-master-service
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redismaster
  type: ClusterIP
