kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/usr/share/redis"
