apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redishanginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redishanginx
    spec:
      containers:
        - name: redishanginx
          image: aozdemir/redishanginx:v1
          resources:
            limits:
              cpu: "1"
              memory: "800Mi"
            requests:
              cpu: "0.5"
              memory: "200Mi"
          ports:
            - containerPort: 80
          

---
apiVersion: v1
kind: Service
metadata:
  name: redishanginx-service
  labels:
    name: redishanginx-service
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: redishanginx
  type: ClusterIP